# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 261700f457773d3c1e8bb21a84a2f114a56ea0d59b2404a7b3a4ec509937608157846601c5c4a799e83933402fd23f10f3f7ee790eaf27c85fb7935ee74c9ce3

test:
  secret_key_base: 14fe2499d15aa296f5169d62aec9e1a22f9b0c249d894b93e64dc7eb57e24878f35d062e4ee053b8d700f722366dca983e6a073e8a7e4b969aaf24c8169696a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
